heat_template_version: 2013-05-23

description: >
  This script creates a virtual machine server on which it starts
  a server using the server.py script

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: INF4410-17
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    default: INF4410-Ubuntu-trusty-mini
    constraints:
      - custom_constraint: glance.image
  network:
    type: string
    description: Network the virtual machine will be on
    default: inf4410-net
  python_script_url:
    type: string
    description: Location of the script to be executed on the machine
    default: https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: {get_param: network }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            wget $python_script_location
            python server.py
          params:
            $python_script_location: {get_param: python_script_url }

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
